tap "homebrew/bundle"
tap "homebrew/services"
tap "mongodb/brew"
brew "cocoapods"
brew "gh"
brew "git-quick-stats"
brew "lazygit"
brew "node"
brew "neovim"
brew "nvm"
brew "powerlevel10k"
brew "ripgrep"
brew "tmux"
cask "iTerm2"

